import type { Metadata } from "next";
import Sidebar from "./_components/sidebar";
import { Navbar } from "./_components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-screen grid grid-cols-6">
      <Sidebar />
      <div className="col-span-5">
        <Navbar />
        {children}
      </div>
    </div>
  );
}
